#!/bin/bash
# Restaurant Image Sourcing Helper
# Usage: ./source-restaurant-images.sh

echo "=== RESTAURANT IMAGE SOURCING GUIDE ==="
echo ""
echo "Priority restaurants to source:"
echo ""
echo "1. Don Julio (@donjulioparrilla)"
echo "   https://instagram.com/donjulioparrilla"
echo "   Target: Interior or signature bife de chorizo"
echo "   Save: restaurants/don-julio.webp"
echo ""
echo "2. La Cabrera (@lacabrera_ba)"
echo "   https://instagram.com/lacabrera_ba"
echo "   Target: Happy hour atmosphere or steak"
echo "   Save: restaurants/la-cabrera.webp"
echo ""
echo "3. Tegui (@tegui)"
echo "   https://instagram.com/tegui"
echo "   Target: Fine dining tasting menu presentation"
echo "   Save: restaurants/tegui.webp"
echo ""
echo "4. El Preferido (@elpreferidodepalermo)"
echo "   https://instagram.com/elpreferidodepalermo"
echo "   Target: Historic bodegón interior"
echo "   Save: restaurants/el-preferido.webp"
echo ""
echo "5. Cafe Registrado (@caferegistrado)"
echo "   https://instagram.com/caferegistrado"
echo "   Target: Third-wave coffee, barista shots"
echo "   Save: restaurants/cafe-registrado.webp"
echo ""
echo "6. Cafe Tortoni (@cafetortoni)"
echo "   https://instagram.com/cafetortoni"
echo "   Target: Historic 1858 interior, stained glass"
echo "   Save: restaurants/cafe-tortoni.webp"
echo ""
echo "7. Aramburu (@arambururesto)"
echo "   https://instagram.com/arambururesto"
echo "   Target: 2 Michelin star artistic dishes"
echo "   Save: restaurants/aramburu.webp"
echo ""
echo "=== WORKFLOW ==="
echo "1. Open Instagram link in browser"
echo "2. Find best representative image"
echo "3. Right-click > 'Open image in new tab' for full-res"
echo "4. Download and convert to WebP:"
echo "   cwebp -q 85 input.jpg -o output.webp"
echo "5. Save to: public/images/restaurants/[slug].webp"
echo "6. Add attribution to lib/data/restaurant-images.ts"
echo ""
